[package]
name = "rst-entities"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dtd-rs = "0.1.0-alpha2"
